package aktie.index;

import java.io.IOException;
import java.util.List;

import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.search.Sort;

import aktie.data.CObj;

public interface IndexInterface
{

    public CObjList getMemMissingSeqNumbers ( String ident, int max );
    public CObjList getSubMissingSeqNumbers ( String ident, int max );
    public CObjList getPubMissingSeqNumbers ( String ident, int max );
    public CObjList getCommunitySeqNumbers ( String ident, String comid, long lastseq, long curseq );
    public CObjList getGlobalMemSeqNumbers ( String ident, long lastseq, long curseq );
    public CObjList getGlobalSubSeqNumbers ( String ident, long lastseq, long curseq );
    public CObjList getGlobalPubSeqNumbers ( String ident, long lastseq, long curseq );
    public CObjList getAllCObj();
    public CObjList getAllPrivIdents();
    public CObjList getPrivateMsgIdentForIdentity ( String id );
    public CObjList getPrivateMyMsgIdentity ( String msgid, Sort s );
    public CObj getPrivateMsgIdentity ( String creator, String msgid );
    public CObjList getPrivateMsgNotDecoded ( String id );
    public CObjList getIdentities();
    public CObjList getZeroIdentities();
    public CObjList getCreatedBy ( String id );
    public CObjList getDecodedPrvIdentifiers();
    public CObjList getDecodedPrvMessages ( String mid, Sort s );
    public CObjList getSubscriptions ( String creator, long first, long last );
    public CObjList getCommunities ( String creator, long first, long last );
    public CObjList getPrvIdent ( String creator, long first, long last );
    public CObjList getAllSpamEx();
    public CObj getLastGlobalSequence ( String creator );
    public CObj getLastCreated ( String type, String creator );
    public CObjList getSpamEx ( String creator, long first, long last );
    public CObjList getPrvMsg ( String creator, long first, long last );
    public CObjList getMemberships ( String creator, long first, long last );
    public CObjList getIdentityPrivateCommunities ( String creator );
    public CObjList getPublicCommunities();
    public CObjList getValidCommunities();
    public CObjList getIdentityMemberships ( String memid );
    public CObjList getMemberships ( String comid, Sort s );
    public CObjList getMyMemberships ( Sort s );
    public CObjList getMyValidMemberships ( Sort s );
    public CObjList getPublicCommunities ( Sort s );
    public CObjList getMyMemberships ( String comid );
    public CObjList searchIdentities ( String squery, Sort s );
    public CObjList searchSemiPrivateCommunities ( String squery,  Sort s );
    public CObjList searchSubscribable ( String squery, String memid, boolean prv, boolean pub, Sort s );
    public CObjList getQueries ( String comid );
    public CObjList getAutodownloadQueries();
    public CObjList searchPostsQuery ( List<CObj> qlst, Sort srt );
    public CObjList searchPosts ( String comid, String qstr, Sort srt );
    public CObj getField ( String id );
    public CObjList searchFields ( String comid, String qstr, Sort srt );
    public CObj getFileInfo ( String id );
    public CObjList searchFiles ( String comid, String share, String qstr, Sort srt );
    public CObjList getSubscriptions ( String comid, Sort s );
    public CObjList getSubsUnsubs ( String comid );
    public CObjList getAllSubscriptions ( );
    public CObjList getMySubscriptions ( String comid );
    public CObjList getMySeqSubscriptions ( String creator, long num );
    public CObjList getDefFields ( String comid );
    public CObjList getMemberSubscriptions ( String memid );
    public CObjList getMySubscriptions();
    public CObjList getFragments ( String wdig, String pdig );
    public CObj getFragment ( String comid, String wdig, String ddig, String dig );
    public CObjList getFragmentsComplete ( String comid, String wdig, String fdig );
    public CObjList getFragmentsToRequest ( String comid, String wdig, String fdig );
    public CObjList getFragmentsToReset ( String comid, String wdig, String fdig );
    public CObjList getFragments ( String digs );
    public CObjList getPosts ( String comid, String memid, long first, long last );
    public CObjList getHasFiles ( String comid, String memid, long first, long last );
    public CObjList getHasFiles ( String comid, String wdig, String pdig );
    public CObjList getHasFiles ( String comid, String wdig, String pdig, Sort s );
    public CObjList getMyHasFiles ( String comid, String wdig, String pdig );
    public CObjList getAllMyHasFiles ( );
    public CObjList getAllMyDuplicates ( );
    public CObjList getAllHasFiles ( );
    public CObjList getAllPosts ( );
    public CObjList getMyHasFiles ( String wdig, String pdig );
    public CObjList getLocalHasFiles ( String comid, String memid, String localfile );
    public CObjList getDuplicate ( String comid, String memid, String localfile );
    public CObj getDuplicate ( String refid, String localfile );
    public CObj getIdentHasFile ( String comid, String uid, String wdig, String pdig );
    public CObj getIdentity ( String id );
    public CObj getMyIdentity ( String id );
    public CObjList getMyIdentities();
    public CObj getCommunity ( String comid );
    public CObjList getUnDecodedMemberships ( long lastdec );
    public CObjList getMembership ( String comid, String memid );
    public CObjList getInvalidMembership ( String comid, String memid );
    public CObjList getPushesToSend();
    public CObjList getPushesToConnect();
    public CObjList getInvalidMemberships();
    public CObjList getInvalidSubscriptions();
    public CObj getSubscription ( String comid, String memid );
    public CObj getSubscriptionUnsub ( String comid, String memid );
    public CObj getByDig ( String dig );
    public CObj getById ( String dig );
    public void indexNoCommit ( IndexWriter idx, CObj o, boolean onlynew ) throws IOException;
    public void delete ( CObj o ) throws IOException;
    public void index ( CObj o, boolean onlynew ) throws IOException;
    public void index ( List<CObj> l, boolean onlynew ) throws IOException;
    public void index ( CObj o ) throws IOException;
    public void index ( List<CObj> l ) throws IOException;
    public CObjList getAllSpamEx ( String creator );

}
